const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const state={market:"NQ",tf:"1H",source:null,bars:[],models:[],archive:[],outcomes:[],research:[],paper:null,selectedModel:null,snapshot:null,mode:"live",pd:{},viewCount:140,offset:0,hover:null,drag:null,lastResearchStates:{},alerts:false,pdOn:true,sessions:true};
const fmt=(v,n=2)=>v===null||v===undefined||v===""?"—":Number(v).toFixed(n);
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
const iso=t=>{try{return new Date(typeof t==="number"&&t>1e12?t:Number(t)||t).toLocaleString("de-DE",{day:"2-digit",month:"2-digit",hour:"2-digit",minute:"2-digit"})}catch{return"—"}};
function log(s){$("#logs").textContent=`[${new Date().toLocaleTimeString()}] ${s}\n`+$("#logs").textContent.slice(0,5000)}
function toast(s){const e=$("#toast");e.textContent=s;e.classList.add("show");setTimeout(()=>e.classList.remove("show"),2800)}
function dot(id,cl){$(id).className=cl}
async function api(path){const r=await fetch(path,{cache:"no-store"});if(!r.ok)throw Error(`${r.status} ${path}`);return r.json()}
function setMarket(m){state.market=m;$$(".marketbar button").forEach(b=>b.classList.toggle("active",b.dataset.market===m));state.offset=0;state.viewCount=140;loadBars();loadPD()}
function setTF(tf){state.tf=tf;$$(".tfbar button").forEach(b=>b.classList.toggle("active",b.dataset.tf===tf));state.offset=0;state.viewCount=140;loadBars()}
function healthFromBoot(d){const ss=d.signal_status||{};dot("#liveDot",ss.running===false?"warn":"ok");const ps=(d.paper||{}).status||{};dot("#paperDot",ps.running?"ok":"warn");const j=(d.research||[])[0];dot("#researchDot",j&&String(j.state).toUpperCase()==="RUNNING"?"ok":"warn")}
async function bootstrap(){
 try{
  const d=await api("/api/bootstrap");$("#version").textContent=d.version+" · parallel UI";state.models=d.models||[];state.archive=d.archive||[];state.outcomes=d.outcome_summary||[];state.research=d.research||[];state.paper=d.paper||null;healthFromBoot(d);
  renderModels();renderSignals();renderArchive();renderOutcomes();renderResearch();renderPaperSummary(d.paper);checkResearchAlerts(state.research);
 }catch(e){log("Bootstrap Fehler: "+e);dot("#liveDot","bad")}
}
async function pollModels(){
 try{const d=await api("/api/models");state.models=d.models||[];renderModels();renderSignals();dot("#liveDot",d.status?.running===false?"warn":"ok")}catch(e){dot("#liveDot","bad")}
}
async function pollResearch(){
 try{const d=await api("/api/research?limit=12");state.research=d.jobs||[];renderResearch();checkResearchAlerts(state.research);const j=state.research[0];dot("#researchDot",j&&String(j.state).toUpperCase()==="RUNNING"?"ok":"warn")}catch(e){}
}
async function pollPaper(){
 try{const d=await api("/api/paper");state.paper=d;renderPaper(d);const s=d.status||{};dot("#paperDot",s.running?"ok":"warn")}catch(e){}
}
async function refreshArchive(){
 try{const d=await api("/api/archive?limit=500");state.archive=d.rows||[];renderArchive()}catch(e){}
}
async function refreshOutcomes(){
 try{const d=await api("/api/outcomes");state.outcomes=d.summary||[];renderOutcomes()}catch(e){}
}
function checkResearchAlerts(jobs){
 for(const j of jobs||[]){const id=j.job_id||"";const st=String(j.state||"");const prev=state.lastResearchStates[id];if(prev&&prev!==st&&["COMPLETED","FAILED","CANCELLED"].includes(st.toUpperCase())){const msg=`Research ${st}: ${j.request?.preset||j.kind||id}`;toast(msg);if(state.alerts&&Notification.permission==="granted")new Notification("TMBT Research",{body:msg})}state.lastResearchStates[id]=st}
}
async function loadBars(){
 if(state.mode==="snapshot")return;
 $("#chartTitle").textContent=`${state.market} · ${state.tf}`;$("#chartEmpty").textContent="Lade Bars…";$("#chartEmpty").style.display="grid";
 try{const d=await api(`/api/bars?market=${encodeURIComponent(state.market)}&tf=${encodeURIComponent(state.tf)}&limit=1500${state.source?`&source=${encodeURIComponent(state.source)}`:""}`);state.bars=d.bars||[];state.source=d.source||null;$("#chartSource").textContent=state.source?`${state.source} · lokaler Cache`:(d.note||"kein Feed");$("#chartEmpty").style.display=state.bars.length?"none":"grid";if(state.bars.length){const p=state.bars.at(-1).c;$("#q"+state.market).textContent=fmt(p,2)}draw()}catch(e){$("#chartEmpty").textContent="Bars konnten nicht geladen werden";log(String(e))}
}
async function loadPD(){
 try{const d=await api(`/api/pd?market=${encodeURIComponent(state.market)}${state.source?`&source=${encodeURIComponent(state.source)}`:""}`);state.pd=d.levels||{};renderPD();draw()}catch(e){state.pd={};renderPD()}
}
function rangeText(h,l){return h==null||l==null?"—":`${fmt(h,2)} / ${fmt(l,2)}`}
function posText(eq){if(eq==null||!state.bars.length)return"—";const p=Number(state.bars.at(-1).c);return p>eq?"Premium":p<eq?"Discount":"EQ"}
function renderPD(){const p=state.pd||{};$("#pm").textContent=rangeText(p.PMH,p.PML);$("#pw").textContent=rangeText(p.PWH,p.PWL);$("#pd").textContent=rangeText(p.PDH,p.PDL);$("#pmPos").textContent=posText(p.month_eq);$("#pwPos").textContent=posText(p.week_eq);$("#pdPos").textContent=posText(p.day_eq)}
function renderModels(){const box=$("#modelList");if(!state.models.length){box.innerHTML='<div class="empty">Keine Live-Modelle gefunden.</div>';return}box.innerHTML=state.models.map(m=>`<div class="model-card ${state.selectedModel?.id===m.id?"selected":""}" data-id="${esc(m.id)}"><div class="model-row"><b>${esc(m.name)}</b><span class="pill ${String(m.status).toLowerCase()}">${esc(m.status)}</span></div><div class="model-row"><small>${esc(m.market)} · ${esc(m.tf)} · ${esc(m.source||"")}</small><small>${esc(m.side)}</small></div></div>`).join("");box.querySelectorAll(".model-card").forEach(el=>el.onclick=()=>selectModel(el.dataset.id))}
function selectModel(id){const m=state.models.find(x=>String(x.id)===String(id));if(!m)return;state.selectedModel=m;state.snapshot=null;state.mode="live";$("#snapshotBanner").classList.remove("show");if(["NQ","ES","XAU"].includes(String(m.market)))state.market=String(m.market);if(m.tf)state.tf=String(m.tf);state.source=m.source||state.source;$$(".marketbar button").forEach(b=>b.classList.toggle("active",b.dataset.market===state.market));$$(".tfbar button").forEach(b=>b.classList.toggle("active",b.dataset.tf===state.tf));$("#selectedSetup").textContent=m.name;$("#selectedState").textContent=`${m.status} · ${m.side}`;renderInspector(m);renderModels();loadBars();loadPD()}
function renderInspector(m, snap=null){if(!m){return}const validity=m.validity||{};$("#inspector").className="inspector";$("#inspector").innerHTML=`<span class="pill ${String(m.status||m.stage).toLowerCase()}">${esc(m.status||m.stage||"—")}</span><h3>${esc(m.name||m.label||m.model||"Setup")}</h3><p>${esc(m.message||validity.reason||"")}</p>`;$("#iEntry").textContent=fmt(m.entry??m.arrays?.entry,4);$("#iStop").textContent=fmt(m.sl??m.stop??m.arrays?.stop,4);$("#iTarget").textContent=fmt(m.tp??m.target??m.arrays?.target,4);$("#iRR").textContent=fmt(m.rr??m.planned_rr??m.arrays?.planned_rr,2);const crit=m.criteria||snap?.criteria||[];$("#criteria").innerHTML=crit.length?crit.slice(0,12).map(c=>{if(typeof c==="string")return`<p class="pass">${esc(c)}</p>`;const s=String(c.status||"PENDING").toLowerCase();return`<p class="${s}"><b>${esc(c.label||c.name||"")}</b>${c.detail?` — ${esc(c.detail)}`:""}</p>`}).join(""):"<p>Keine Kriterien verfügbar.</p>";const logic=m.logic||snap?.logic||{};const entries=Object.entries(logic);$("#logic").innerHTML=entries.length?entries.slice(0,12).map(([k,v])=>`<p><b>${esc(k)}:</b> ${esc(typeof v==="object"?JSON.stringify(v):v)}</p>`).join(""):"<p>Keine Logikdetails verfügbar.</p>"}
function renderSignals(){const rows=state.models.map(m=>`<tr class="clickable" data-id="${esc(m.id)}"><td>${esc(m.name)}</td><td>${esc(m.market)}</td><td>${esc(m.tf)}</td><td><span class="pill ${String(m.status).toLowerCase()}">${esc(m.status)}</span></td><td>${esc(m.side)}</td><td>${fmt(m.entry,4)}</td><td>${fmt(m.sl,4)}</td><td>${fmt(m.tp,4)}</td><td>${fmt(m.rr,2)}</td><td class="muted">${esc(m.message)}</td></tr>`).join("");$("#signalsTable").innerHTML=`<table class="table"><thead><tr><th>Model</th><th>Market</th><th>TF</th><th>Status</th><th>Side</th><th>Entry</th><th>SL</th><th>TP</th><th>RR</th><th>Info</th></tr></thead><tbody>${rows}</tbody></table>`;$("#signalsTable").querySelectorAll("tr[data-id]").forEach(r=>r.onclick=()=>selectModel(r.dataset.id))}
function archiveFiltered(){const q=$("#archiveSearch")?.value.toLowerCase()||"",st=$("#archiveStage")?.value||"";return state.archive.filter(r=>(!st||String(r.stage)===st)&&(!q||[r.model,r.market,r.stage,r.side,r.reason].some(x=>String(x||"").toLowerCase().includes(q))))}
function renderArchive(){if(!$("#archiveTable"))return;const arr=archiveFiltered();$("#archiveCount").textContent=`${arr.length} Einträge`;const rows=arr.map(r=>`<tr class="clickable" data-hid="${esc(r.history_id)}" data-sid="${esc(r.snapshot_id||"")}"><td>${r.snapshot_id?"📸":"—"}</td><td>${iso(r.event_time_utc)}</td><td>${esc(r.model)}</td><td>${esc(r.market)}</td><td>${esc(r.tf)}</td><td><span class="pill ${String(r.stage).toLowerCase()}">${esc(r.stage)}</span></td><td>${esc(r.side||"—")}</td><td>${fmt(r.entry,4)}</td><td>${fmt(r.sl,4)}</td><td>${fmt(r.tp,4)}</td><td>${r.outcome?esc(r.outcome):"—"}</td><td class="${Number(r.outcome_r)>0?"good":Number(r.outcome_r)<0?"bad":""}">${r.outcome_r==null?"—":fmt(r.outcome_r,2)+"R"}</td><td class="muted">${esc(r.reason||"")}</td></tr>`).join("");$("#archiveTable").innerHTML=`<table class="table"><thead><tr><th>Snap</th><th>Zeit</th><th>Model</th><th>Mkt</th><th>TF</th><th>Status</th><th>Side</th><th>Entry</th><th>SL</th><th>TP</th><th>Outcome</th><th>R</th><th>Grund</th></tr></thead><tbody>${rows}</tbody></table>`;$("#archiveTable").querySelectorAll("tr[data-hid]").forEach(r=>r.onclick=()=>openArchive(r.dataset.hid,r.dataset.sid))}
async function openArchive(hid,sid){const row=state.archive.find(x=>x.history_id===hid);if(!row)return;if(!sid){toast("Für diesen Legacy-Eintrag existiert kein eingefrorener Snapshot.");return}try{const snap=await api(`/api/snapshot?id=${encodeURIComponent(sid)}`);state.snapshot=snap;state.mode="snapshot";state.bars=(snap.bars||[]).map(b=>({t:b.bar_open_ms??b.t,o:Number(b.open??b.o),h:Number(b.high??b.h),l:Number(b.low??b.l),c:Number(b.close??b.c)}));state.offset=0;state.viewCount=Math.min(140,Math.max(40,state.bars.length));const sm=snap.model||{};state.market=sm.market||row.market||state.market;state.tf=sm.timeframe||row.tf||state.tf;state.selectedModel={id:row.model_id||hid,name:sm.label||row.model,status:sm.stage||row.stage,side:sm.side||row.side,entry:snap.arrays?.entry??row.entry,sl:snap.arrays?.stop??row.sl,tp:snap.arrays?.target??row.tp,rr:snap.arrays?.planned_rr??row.rr,message:sm.message||row.reason,criteria:snap.criteria||row.criteria,logic:snap.logic||row.logic,arrays:snap.arrays||{},validity:snap.validity||{}};$("#snapshotBanner").classList.add("show");$("#snapshotName").textContent=`${state.selectedModel.name} · ${iso(snap.event_time_utc)}`;$("#chartTitle").textContent=`${state.market} · ${state.tf} · Snapshot`;$("#chartSource").textContent=`eingefroren · ${sm.source||row.source||"—"}`;$("#selectedSetup").textContent=state.selectedModel.name;$("#selectedState").textContent=`${state.selectedModel.status} · ${state.selectedModel.side}`;renderInspector(state.selectedModel,snap);$("#chartEmpty").style.display=state.bars.length?"none":"grid";draw();toast("Snapshot geladen")}catch(e){toast("Snapshot konnte nicht geladen werden.");log(String(e))}}
function backLive(){state.mode="live";state.snapshot=null;$("#snapshotBanner").classList.remove("show");state.offset=0;loadBars();loadPD();if(state.selectedModel)renderInspector(state.selectedModel)}
function renderOutcomes(){const arr=state.outcomes||[];$("#outcomeCards").className="outcome-grid";$("#outcomeCards").innerHTML=arr.length?arr.map(o=>`<div class="outcome-card"><h4>${esc(o.model)}</h4><div class="mini-grid"><div><small>Signals</small><b>${o.signals}</b></div><div><small>Winrate</small><b>${o.winrate==null?"—":fmt(o.winrate,1)+"%"}</b></div><div><small>Net R</small><b class="${o.net_r>0?"good":o.net_r<0?"bad":""}">${fmt(o.net_r,2)}R</b></div><div><small>Expectancy</small><b>${o.expectancy==null?"—":fmt(o.expectancy,2)+"R"}</b></div><div><small>Ø MFE</small><b>${o.avg_mfe==null?"—":fmt(o.avg_mfe,2)+"R"}</b></div><div><small>Ø MAE</small><b>${o.avg_mae==null?"—":fmt(o.avg_mae,2)+"R"}</b></div></div></div>`).join(""):'<div class="empty">Noch keine Outcome-Daten.</div>'}
function renderResearch(){const arr=state.research||[];$("#researchList").innerHTML=arr.length?arr.map(j=>{const p=j.progress||{},pct=Number(p.pct||0);return`<div class="research-card"><div class="model-row"><h4>${esc(j.request?.preset||j.kind||j.job_id)}</h4><span class="pill ${String(j.state).toLowerCase()}">${esc(j.state)}</span></div><div class="progress"><i style="width:${Math.max(0,Math.min(100,pct))}%"></i></div><div class="model-row"><small>${pct.toFixed(1)}% · ${esc(p.date||"")} · Trades ${p.trades??"—"}</small><small>${esc(j.job_id||"")}</small></div>${j.error?`<p class="bad">${esc(j.error)}</p>`:""}</div>`}).join(""):'<div class="empty">Keine Research-Jobs gefunden.</div>'}
function renderPaperSummary(p){state.paper=p;renderPaper(p)}
function renderPaper(d){if(!d)return;const status=d.status||{},s=d.state||{},cfg=d.config||{},opens=Array.isArray(s.open_positions)?s.open_positions:[],trades=d.trades||[];const top=`<div class="paper-top"><div><small>Agent</small><b>${esc(status.state||"—")}</b></div><div><small>Balance</small><b>${fmt(s.balance??status.balance,2)}</b></div><div><small>Equity</small><b>${fmt(s.equity??status.equity,2)}</b></div><div><small>Open</small><b>${opens.length}</b></div><div><small>Net R</small><b>${fmt(s.net_r,2)}R</b></div></div>`;const openRows=opens.map(p=>`<tr><td>${esc(p.model||p.model_id)}</td><td>${esc(p.side)}</td><td>${fmt(p.entry,4)}</td><td>${fmt(p.current_price,4)}</td><td>${fmt(p.stop,4)}</td><td>${fmt(p.target,4)}</td><td>${p.unrealized_r==null?"—":fmt(p.unrealized_r,2)+"R"}</td></tr>`).join("");const closedRows=trades.slice(0,20).map(t=>`<tr><td>${esc(t.model||t.model_id)}</td><td>${esc(t.side)}</td><td>${esc(t.exit_reason||t.status||"")}</td><td>${t.r==null?"—":fmt(t.r,2)+"R"}</td><td>${iso(t.exit_time_utc||t.closed_at_utc)}</td></tr>`).join("");$("#paperView").innerHTML=top+`<h4>Offene Demo-Trades</h4><table class="table"><thead><tr><th>Model</th><th>Side</th><th>Entry</th><th>Current</th><th>SL</th><th>TP</th><th>uR</th></tr></thead><tbody>${openRows||'<tr><td colspan="7" class="muted">Keine offenen Positionen</td></tr>'}</tbody></table><h4>Letzte geschlossene Trades</h4><table class="table"><thead><tr><th>Model</th><th>Side</th><th>Exit</th><th>R</th><th>Zeit</th></tr></thead><tbody>${closedRows||'<tr><td colspan="5" class="muted">Noch keine geschlossenen Trades</td></tr>'}</tbody></table>`}
function arrLines(){const m=state.selectedModel,a=state.snapshot?.arrays||m?.arrays||{};const lines=[];const push=(label,v,col,dash=true)=>{if(v!=null&&isFinite(Number(v)))lines.push({label,v:Number(v),col,dash})};push("ENTRY",a.entry??m?.entry,"#5fa9ff");push("SL",a.stop??m?.sl,"#ff6575");push("TP",a.target??m?.tp,"#2fcf8b");if(state.pdOn){push("PDH",state.pd.PDH,"#657790");push("PDL",state.pd.PDL,"#657790");push("PWH",state.pd.PWH,"#7e6ac7");push("PWL",state.pd.PWL,"#7e6ac7");push("PMH",state.pd.PMH,"#9a6c9b");push("PML",state.pd.PML,"#9a6c9b");push("Ref H",a.reference_high,"#8c78d8");push("Ref L",a.reference_low,"#8c78d8");push("OTE H",a.zone_high,"#6d7fd1");push("OTE L",a.zone_low,"#6d7fd1");push("iFVG H",a.ifvg_high,"#bb7f4b");push("iFVG L",a.ifvg_low,"#bb7f4b");push("Prev H",a.prev_high,"#6f8198");push("Prev L",a.prev_low,"#6f8198")}return lines}
function visibleBars(){const n=state.bars.length;if(!n)return[];const count=Math.min(state.viewCount,n),end=Math.max(count,n-state.offset),start=Math.max(0,end-count);return state.bars.slice(start,end)}
function draw(){const cv=$("#chart"),host=$("#chartHost"),dpr=devicePixelRatio||1,w=Math.max(300,host.clientWidth),h=Math.max(160,host.clientHeight);cv.width=w*dpr;cv.height=h*dpr;cv.style.width=w+"px";cv.style.height=h+"px";const x=cv.getContext("2d");x.scale(dpr,dpr);x.clearRect(0,0,w,h);x.strokeStyle="#182435";x.lineWidth=1;for(let i=1;i<8;i++){let y=i*h/8;x.beginPath();x.moveTo(0,y);x.lineTo(w,y);x.stroke()}for(let i=1;i<12;i++){let xx=i*w/12;x.beginPath();x.moveTo(xx,0);x.lineTo(xx,h);x.stroke()}const b=visibleBars();if(!b.length){$("#chartEmpty").style.display="grid";return}$("#chartEmpty").style.display="none";let lo=Math.min(...b.map(z=>z.l)),hi=Math.max(...b.map(z=>z.h));for(const l of arrLines()){lo=Math.min(lo,l.v);hi=Math.max(hi,l.v)}const pad=(hi-lo)*.06||1;lo-=pad;hi+=pad;const top=25,bottom=h-23,sy=v=>top+(hi-v)/(hi-lo)*(bottom-top),step=w/b.length,bw=Math.max(2,Math.min(9,step*.66));if(state.sessions&&state.mode==="live"){x.fillStyle="rgba(70,145,220,.035)";x.fillRect(w*.58,top,w*.10,bottom-top)}b.forEach((z,i)=>{const cx=i*step+step/2,up=z.c>=z.o,col=up?"#2bc889":"#ff6171";x.strokeStyle=col;x.fillStyle=col;x.setLineDash([]);x.beginPath();x.moveTo(cx,sy(z.h));x.lineTo(cx,sy(z.l));x.stroke();const y1=sy(Math.max(z.o,z.c)),y2=sy(Math.min(z.o,z.c));x.fillRect(cx-bw/2,y1,bw,Math.max(1,y2-y1))});x.font="10px Segoe UI";for(const l of arrLines()){const y=sy(l.v);x.strokeStyle=l.col;x.fillStyle=l.col;x.setLineDash(l.dash?[5,5]:[]);x.beginPath();x.moveTo(0,y);x.lineTo(w,y);x.stroke();x.setLineDash([]);x.fillText(`${l.label} ${fmt(l.v,2)}`,Math.max(5,w-105),y-3)}const ticks=5;x.fillStyle="#77889e";for(let i=0;i<ticks;i++){const idx=Math.round(i*(b.length-1)/(ticks-1)),z=b[idx],xx=idx*step+step/2;x.fillText(iso(z.t),Math.max(2,xx-28),h-7)}if(state.hover!=null&&state.hover>=0&&state.hover<b.length){const i=state.hover,z=b[i],cx=i*step+step/2,cy=sy(z.c);x.strokeStyle="#607188";x.setLineDash([3,4]);x.beginPath();x.moveTo(cx,top);x.lineTo(cx,bottom);x.moveTo(0,cy);x.lineTo(w,cy);x.stroke();x.setLineDash([]);$("#ohlcText").textContent=`O ${fmt(z.o,2)}  H ${fmt(z.h,2)}  L ${fmt(z.l,2)}  C ${fmt(z.c,2)}`;$("#cursorTime").textContent=iso(z.t)}}
function chartMouse(e){const rect=$("#chart").getBoundingClientRect(),b=visibleBars();if(!b.length)return;state.hover=Math.max(0,Math.min(b.length-1,Math.floor((e.clientX-rect.left)/rect.width*b.length)));draw()}
function wheel(e){e.preventDefault();const dir=e.deltaY>0?1:-1;state.viewCount=Math.max(30,Math.min(400,state.viewCount+dir*15));draw()}
function dragStart(e){state.drag={x:e.clientX,offset:state.offset}}
function dragMove(e){if(!state.drag)return;const host=$("#chartHost"),pxPer=Math.max(2,host.clientWidth/Math.max(1,state.viewCount)),delta=Math.round((e.clientX-state.drag.x)/pxPer);state.offset=Math.max(0,Math.min(Math.max(0,state.bars.length-state.viewCount),state.drag.offset-delta));draw()}
function dragEnd(){state.drag=null}
function fit(){state.offset=0;state.viewCount=Math.min(160,Math.max(40,state.bars.length));draw()}
function setupSplit(id,varName,type){const el=$(id);let start,initial;el.onmousedown=e=>{e.preventDefault();start=type==="h"?e.clientY:e.clientX;initial=parseFloat(getComputedStyle(document.documentElement).getPropertyValue(varName));const move=ev=>{let v=initial;if(varName==="--left")v+=ev.clientX-start;if(varName==="--right")v-=ev.clientX-start;if(varName==="--bottom")v-=ev.clientY-start;v=Math.max(varName==="--bottom"?40:0,Math.min(varName==="--bottom"?520:560,v));document.documentElement.style.setProperty(varName,v+"px");draw()};const up=()=>{document.removeEventListener("mousemove",move);document.removeEventListener("mouseup",up)};document.addEventListener("mousemove",move);document.addEventListener("mouseup",up)}}
$$(".marketbar button").forEach(b=>b.onclick=()=>setMarket(b.dataset.market));$$(".tfbar button").forEach(b=>b.onclick=()=>setTF(b.dataset.tf));$$(".quotes>div").forEach(d=>d.onclick=()=>setMarket(d.dataset.goto));$$(".bottom-tabs button[data-tab]").forEach(b=>b.onclick=()=>{$$(".bottom-tabs button[data-tab]").forEach(x=>x.classList.toggle("active",x===b));$$(".tab").forEach(t=>t.classList.remove("active"));$("#tab-"+b.dataset.tab).classList.add("active");if(b.dataset.tab==="archive")refreshArchive();if(b.dataset.tab==="outcomes")refreshOutcomes();if(b.dataset.tab==="paper")pollPaper();if(b.dataset.tab==="research")pollResearch()});
$("#archiveSearch").oninput=renderArchive;$("#archiveStage").onchange=renderArchive;$("#backLive").onclick=backLive;$("#liveModeBtn").onclick=backLive;$("#fitBtn").onclick=fit;$("#pdBtn").onclick=()=>{state.pdOn=!state.pdOn;$("#pdBtn").classList.toggle("active",state.pdOn);draw()};$("#sessionsBtn").onclick=()=>{state.sessions=!state.sessions;$("#sessionsBtn").classList.toggle("active",state.sessions);draw()};$("#leftHide").onclick=()=>document.body.classList.toggle("left-collapsed");$("#rightHide").onclick=()=>document.body.classList.toggle("right-collapsed");$("#bottomHide").onclick=()=>document.body.classList.toggle("bottom-collapsed");
$("#alertsBtn").onclick=async()=>{if(!("Notification" in window)){toast("Browser unterstützt keine Notifications.");return}const p=await Notification.requestPermission();state.alerts=p==="granted";$("#alertsBtn").classList.toggle("active",state.alerts);toast(state.alerts?"Alerts aktiviert":"Alerts nicht erlaubt")};
const cv=$("#chart");cv.addEventListener("mousemove",chartMouse);cv.addEventListener("mouseleave",()=>{state.hover=null;draw()});cv.addEventListener("wheel",wheel,{passive:false});cv.addEventListener("mousedown",dragStart);window.addEventListener("mousemove",dragMove);window.addEventListener("mouseup",dragEnd);window.addEventListener("resize",draw);
setupSplit("#splitLeft","--left","v");setupSplit("#splitRight","--right","v");setupSplit("#splitBottom","--bottom","h");
bootstrap();loadBars();loadPD();setInterval(pollModels,2500);setInterval(()=>{if(state.mode==="live")loadBars()},5000);setInterval(pollResearch,5000);setInterval(pollPaper,5000);setInterval(()=>{refreshArchive();refreshOutcomes()},15000);
